# Generated by Django 3.0.9 on 2020-08-29 05:16

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo10',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo11',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo12',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo13',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo14',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo15',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo4',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo5',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo6',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo7',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo8',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo9',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
