# Generated by Django 3.0.9 on 2020-08-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0002_auto_20200828_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
