# Generated by Django 3.0.9 on 2020-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0003_auto_20200828_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.CharField(default=5, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='bedrooms',
            field=models.CharField(default=5, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='house_type',
            field=models.CharField(default='bungalow', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on_market', 'On Market'), ('Sold', 'sold')], default='sold', max_length=20),
        ),
    ]
